# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Martin Schaefer
tagline:          'personal web'
description:      'AI consultant and programmer. You can find me on <a href="https://www.linkedin.com/in/martin-schaefer-251a8741" target="_blank">LinkedIn</a>.'
url:              https://schaefer.cz/
baseurl:          https://schaefer.cz/

author:
  name:           'Martin Schaefer'
  url:            http://schaefer.cz

paginate:         3

# Custom vars
version:          1.0

github:
  repo:           https://github.com/schaemar/www_blog
